# Generated by Django 4.0.3 on 2022-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0003_animeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeentry',
            name='animeID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
