# Generated by Django 4.0.3 on 2022-03-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0006_alter_animeentry_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeentry',
            name='genres',
            field=models.CharField(max_length=16),
        ),
    ]
