# Generated by Django 4.0.3 on 2022-03-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0007_alter_animeentry_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=16)),
                ('genre_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='animeentry',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MARS.genre'),
        ),
    ]
