# Generated by Django 4.0.3 on 2022-03-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0008_genre_alter_animeentry_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeentry',
            name='genres',
        ),
        migrations.AddField(
            model_name='animeentry',
            name='genres',
            field=models.ManyToManyField(to='MARS.genre'),
        ),
    ]
