# Generated by Django 4.0.3 on 2022-03-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0009_remove_animeentry_genres_animeentry_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeentry',
            name='main_picture',
            field=models.CharField(default='https://cdn.myanimelist.net/images/anime/1223/96541.jpg', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animeentry',
            name='synopsis',
            field=models.CharField(default='', max_length=8192),
            preserve_default=False,
        ),
    ]
