# Generated by Django 4.0.3 on 2022-03-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0010_animeentry_main_picture_animeentry_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeentry',
            old_name='animeID',
            new_name='MAL_ID',
        ),
    ]
