# Generated by Django 4.0.3 on 2022-04-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0011_rename_animeid_animeentry_mal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='selected_genres',
            field=models.CharField(default=0, max_length=8192),
            preserve_default=False,
        ),
    ]
