# Generated by Django 4.0.3 on 2022-04-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0012_search_selected_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='animeentry',
            name='media_type',
            field=models.CharField(default='tv', max_length=120),
            preserve_default=False,
        ),
    ]
