# Generated by Django 4.0.3 on 2022-04-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0013_delete_user_animeentry_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='movies',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='onas',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='ovas',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='specials',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='tv',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
