# Generated by Django 4.0.3 on 2022-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0015_animeentry_mean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeentry',
            name='mean',
            field=models.FloatField(),
        ),
    ]
