# Generated by Django 4.0.3 on 2022-04-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MARS', '0016_alter_animeentry_mean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeentry',
            old_name='mean',
            new_name='score',
        ),
    ]
